name: get release

on:
  workflow_dispatch:

env:
  OS_IMAGE_v1_3_x: registry.opensuse.org/isv/rancher/harvester/os/v1.3/main/baseos:latest

jobs:
  package-diff-v1_3:
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/bci-base:15.4

    steps:
      - name: Get v1.3 latest release
        id: get_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const releases = response.data;
            const releaseNameToFind = "v1.3"; // Replace with the name you're searching for

            const foundRelease = releases.find(release => release.name.includes(releaseNameToFind));

            if (foundRelease) {
              const releaseName = foundRelease.name;
              const osImage = `rancher/harvester-os:${foundRelease.name}`;
              core.setOutput('releaseName', releaseName);
              core.setOutput('osImage', osImage);

            } else {
              core.setFailed(`No release found with the name ${releaseNameToFind}`);
            }
      - name: Install docker
        run: zypper ref && zypper -n install docker
      - name: Pull current os image
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          retry_wait_seconds: 60
          command: 'docker pull ${{ steps.get_release.outputs.osImage }}'
      - name: Install container-diff
        run: |
          curl -sfL https://github.com/GoogleContainerTools/container-diff/releases/download/v0.17.0/container-diff-linux-amd64 -o /usr/bin/container-diff
          chmod +x /usr/bin/container-diff
      - name: Run container-diff
        run: |
          docker pull ${{ env.OS_IMAGE_v1_3_x }}
          echo "Diff ${{ env.OS_IMAGE_v1_3_x }} with ${{ steps.get_release.outputs.osImage }}..."
          container-diff diff daemon://docker.io/${{ env.OS_IMAGE_v1_3_x }} daemon://docker.io/${{ steps.get_release.outputs.osImage }} --type=rpm --output=diff-result.txt
          cat diff-result.txt
      
