name: get release

on:
  workflow_dispatch:

jobs:
  get-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get release by name
        id: get_release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const releases = response.data;
            const releaseNameToFind = "YOUR_RELEASE_NAME"; // Replace with the name you're searching for

            const foundRelease = releases.find(release => release.name.includes(releaseNameToFind));
            
            if (foundRelease) {
              console.log(`Found release ${foundRelease.name} with tag ${foundRelease.tag_name}`);
              console.log(`URL: ${foundRelease.html_url}`);
              console.log(`Assets: ${foundRelease.assets.map(asset => asset.name).join(', ')}`);

              // Use echo to set values to GITHUB_OUTPUT
              echo "::set-env name=RELEASE_NAME::${foundRelease.name}"
              echo "::set-env name=TAG_NAME::${foundRelease.tag_name}"
              echo "::set-env name=RELEASE_URL::${foundRelease.html_url}"
            } else {
              echo "No release found with the name ${releaseNameToFind}"
            }

      - name: Show the base image name
        run: echo "BASEOS IMG `rancher/harvester-os:${{ steps.get_release.outputs.release_name }}`"
