name: get release

on:
  workflow_dispatch:

jobs:
  get-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get release by name
        id: get_release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const releases = response.data;
            const releaseNameToFind = "v1.3"; // Replace with the name you're searching for
            const foundRelease = releases.find(release => release.name.includes(releaseNameToFind));

            if (foundRelease) {
              echo "releaseName=v1.3-xxxxxx" >> "$GITHUB_OUTPUT"
            } else {
              console.log(`No release found with the name ${releaseNameToFind}`);
              return { error: `No release found with the name ${releaseNameToFind}` };
            }
      

      - name: Show the base image name
        run: echo "BASEOS IMG `rancher/harvester-os:${{ steps.get_release.outputs.releaseName }}`"
