name: Package Differences

on:
  workflow_dispatch:

env:
  OS_IMAGE_v1_3_x: registry.opensuse.org/isv/rancher/harvester/os/v1.3/main/baseos:latest
  FOUND_DIFF_v1_3_x: 'false'

jobs:
  check-whole-versions-packages-diff:
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/bci-base:15.4

    steps:
      - name: Get all release
        id: get_all_releases
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const releases = response.data;
            core.setOutput('allReleases', releases);
      - name: Get v1.3 latest release
        id: get_release_v1_3_x
        uses: actions/github-script@v6
        with:
          script: |
            core.setOutput('found', false);
            const releases = ${{ steps.get_all_releases.outputs.allReleases }};
            const releaseNameToFind = "v1.3";
            const foundRelease = releases.find(release => release.name.includes(releaseNameToFind));

            if (foundRelease) {
              const releaseName = foundRelease.name;
              const osImage = `rancher/harvester-os:${foundRelease.name}`;
              
              core.setOutput('releaseName', releaseName);
              core.setOutput('osImage', osImage);
              core.setOutput('found', true);
            }
      - name: Install docker
        run: zypper ref && zypper -n install docker
      - name: Install container-diff
        run: |
          curl -sfL https://github.com/GoogleContainerTools/container-diff/releases/download/v0.17.0/container-diff-linux-amd64 -o /usr/bin/container-diff
          chmod +x /usr/bin/container-diff
      - name: Pull current v1.3.x os image
        if: steps.get_release_v1_3_x.outputs.found
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          retry_wait_seconds: 60
          command: 'docker pull ${{ steps.get_release_v1_3_x.outputs.osImage }}'
      - name: Run container-diff for v1.3.x
        if: steps.get_release_v1_3_x.outputs.found
        run: |
          docker pull ${{ env.OS_IMAGE_v1_3_x }}
          echo "Diff ${{ env.OS_IMAGE_v1_3_x }} with ${{ steps.get_release_v1_3_x.outputs.osImage }}..."
          container-diff diff daemon://docker.io/${{ env.OS_IMAGE_v1_3_x }} daemon://docker.io/${{ steps.get_release_v1_3_x.outputs.osImage }} --type=rpm --output=diff-result-v1.3.x.txt
          cat diff-result-v1.3.x.txt
          echo "FOUND_DIFF_v1_3_x=true" >> $GITHUB_ENV
      - name: Upload container-diff result
        if: steps.get_release_v1_3_x.outputs.found
        uses: actions/upload-artifact@v3
        with:
          name: diff-result-v1.3.x
          path: diff-result-v1.3.x.txt
      - name: debug
        if: steps.get_release_v1_3_x.outputs.found
        run: |
          echo "found diff: `${{ env.FOUND_DIFF_v1_3_x }}`"

  show-the-packages-differences:
      needs: check-whole-versions-packages-diff
      runs-on: ubuntu-latest
      
      steps:
        - name: debug
          run: |
            echo "found diff: `${{ env.FOUND_DIFF_v1_3_x }}`"
        - name: Download container-diff result
          if: env.FOUND_DIFF_v1_3_x == 'true'
          uses: actions/download-artifact@v3
          with:
            name: diff-result-v1.3.x
        - name: Read diff result
          if: env.FOUND_DIFF_v1_3_x == 'true'
          id: read
          uses: juliangruber/read-file-action@v1
          with:
            path: ./diff-result-v1.3.x.txt
        - name: Remove unused files
          if: env.FOUND_DIFF_v1_3_x == 'true'
          run: rm diff-result-v1.3.x.txt
        - name: Show output
          if: env.FOUND_DIFF_v1_3_x == 'true'
          run: echo ${{ steps.read.outputs.content }}

