name: get release

on:
  workflow_dispatch:

jobs:
  get-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release by name
        id: get_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const releases = response.data;
            const releaseNameToFind = "YOUR_RELEASE_NAME"; // Replace with the name you're searching for

            const foundRelease = releases.find(release => release.name.includes(releaseNameToFind));

            if (foundRelease) {
              const releaseName = foundRelease.name;
              const tagName = foundRelease.tag_name;
              const releaseUrl = foundRelease.html_url;

              core.setOutput('releaseName', releaseName);
              core.setOutput('tagName', tagName);
              core.setOutput('releaseUrl', releaseUrl);

              console.log(`Found release ${releaseName} with tag ${tagName}`);
              console.log(`URL: ${releaseUrl}`);
              console.log(`Assets: ${foundRelease.assets.map(asset => asset.name).join(', ')}`);
            } else {
              core.setFailed(`No release found with the name ${releaseNameToFind}`);
            }
      
      - name: Show the base image name
        run: echo "BASEOS IMG `rancher/harvester-os:${{ steps.get_release.outputs.releaseName }}`"
