on:
  push:
    tags:
    - v*

env:
  IMAGE_NAME: rancher/harvester-os:${{ github.ref_name }}

jobs:
  create-installer-pr:
    runs-on: ubuntu-latest
    steps:
      - name: setup target branch
        run: echo $(${{ github.ref_name }}%%-*)
      - name: Clone harvester-installer repo
        uses: actions/checkout@v3
        with:
          repository: harvester/harvester-installer
      - name: Update os image
        run: |
          sed -i "s,^BASE_OS_IMAGE=.*,BASE_OS_IMAGE=\"${{ env.IMAGE_NAME }}\"," scripts/package-harvester-os
          echo "patched result: $(grep ^BASE_OS_IMAGE scripts/package-harvester-os)"
