on:
  push:
    tags:
    - v*

env:
  IMAGE_NAME: rancher/harvester-os:${{ github.ref_name }}

jobs:
  create-installer-pr:
    runs-on: ubuntu-latest
    steps:
      - name: running echo
        id: do_echo
        run: |
           echo "running echo"

      - name: Extract branch name
        uses: actions/github-script@v7
        id: get-target-version
        with:
          script: |
            const fullBranchName = context.ref.replace('refs/tags/', '');
            console.log(`Full branch name: ${fullBranchName}`);
            
            const targetVersion = fullBranchName.split('-')[0];
            console.log(`targetVersion: ${targetVersion}`);
            
            core.setOutput('targetVersion', targetVersion);

      - name: Use branch version
        if: steps.do_echo.conclusion == 'success'
        run: |
          echo "The extracted version is: ${{ steps.get-target-version.outputs.targetVersion }}"
